name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm -F website exec playwright install chromium

      - name: Run tests
        run: pnpm test -- --run
        env:
          CI: true
          TURBO_TELEMETRY_DISABLED: 1
          FRONTEND_URL: https://yourvtt.com
          NODE_ENV: test
          CREATE_ROOM_API_KEY: ci-test-api-key
          VITE_CREATE_ROOM_API_KEY: ci-test-api-key
          VITE_API_URL: http://localhost:8787

      - name: Run tests with coverage
        run: pnpm -F website test:coverage
        env:
          CI: true
          NODE_ENV: test
          VITE_CREATE_ROOM_API_KEY: ci-test-api-key
          VITE_API_URL: http://localhost:8787
